// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqsTxZn7b0BEJpYeeAzTdHHj31KqGdM4',
    appId: '1:677557829420:web:1df0c93c6209ff2770f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    authDomain: 'trash-monitoring-app-88131.firebaseapp.com',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    measurementId: 'G-KSBY9Y92VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBES3ugYqnsfFd-EozP0K1Sk-UofX69UAo',
    appId: '1:677557829420:android:1544b281da3f363770f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxyvdi-3GsaDteGRsp6Jwn7iZ7G1LsGYw',
    appId: '1:677557829420:ios:7c0d85951248548e70f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    androidClientId: '677557829420-41qb7kdgnfk3ke6vglccqj67t65qg6bn.apps.googleusercontent.com',
    iosClientId: '677557829420-628kv2basf4ba8uh2s1875uk1rhgejjt.apps.googleusercontent.com',
    iosBundleId: 'com.ascoa.wemonitor',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxyvdi-3GsaDteGRsp6Jwn7iZ7G1LsGYw',
    appId: '1:677557829420:ios:922f6f495f6e9dea70f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    androidClientId: '677557829420-ckmej1rg4iufigts9rq4b7i1ieevma0l.apps.googleusercontent.com',
    iosClientId: '677557829420-m7mqbuukpoljrflq5svhhbt46r6okmcv.apps.googleusercontent.com',
    iosBundleId: 'com.ascoa.wemonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqsTxZn7b0BEJpYeeAzTdHHj31KqGdM4',
    appId: '1:677557829420:web:0e8798b94f74ae2570f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    authDomain: 'trash-monitoring-app-88131.firebaseapp.com',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    measurementId: 'G-N5506207HV',
  );

}
