name: Flutter Release Workflow

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.jks
          ls -l android/app/key.jks

      - name: Generate Splash Screen
        run: flutter pub run flutter_native_splash:create

      - name: Set Version
        run: |
          VERSION_CODE=${GITHUB_RUN_NUMBER}
          SHORT_SHA=$(git rev-parse --short HEAD)
          DATE=$(date +'%Y%m%d.%H%M')
          BRANCH_NAME=${GITHUB_REF##*/}
          VERSION_NAME="1.0.${VERSION_CODE}-${BRANCH_NAME}-${DATE}-g${SHORT_SHA}"
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release --dart-define=GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} --build-name=$VERSION_NAME --build-number=$VERSION_CODE
        env:
          KEYSTORE_FILE: key.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create Release
        run: gh release create "$VERSION_NAME" --title "Test Release $VERSION_NAME" --notes "Automated release from branch $BRANCH_NAME commit $SHORT_SHA" build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
